export const DEFAULT_CONFIG = {
  version: 1,
  colors: {
    brandInk: '#300101',
    brandCanvas: '#FFFEFC',
    actionPrimary: '#2216FF',
    actionPrimaryHover: '#1B11CC',
    textPrimary: '#300101',
    textSecondary: '#64645F',
    textOnDark: '#FFFEFC',
    borderDefault: '#E0E0DC',
    borderFocus: '#2216FF',
  },
  typography: {
    fontFamily: 'Inter',
    headlineSize: '2.25rem',
    formTitleSize: '1.5rem',
    bodySize: '1rem',
    headlineWeight: '700',
  },
  content: {
    logoText: 'klasse',
    logoLetter: 'K',
    headline: 'Create and sell courses in minutes, not months',
    subheadline: 'Join thousands of creators building their knowledge business with Klasse.',
    formTitle: 'Create your account',
    formSubtitle: 'Start building in under 2 minutes',
    submitButtonText: 'Create Account',
    googleButtonText: 'Continue with Google',
    dividerText: 'or sign up with email',
    signinPrompt: 'Already have an account?',
    signinLinkText: 'Sign in',
  },
  cards: [
    { title: 'Introduction to UX Design', instructor: 'Sarah Chen', image: '', visible: true },
    { title: 'Advanced Photography', instructor: 'Marcus Rivera', image: '', visible: true },
    { title: 'Music Production 101', instructor: 'Alex Kim', image: '', visible: true },
  ],
  layout: {
    showBrowserChrome: true,
    showGoogleButton: true,
    showDivider: true,
    showCourseCards: true,
    showTerms: true,
    borderRadius: '8',
    brandPanelPosition: 'left',
  },
}
