export const DEFAULT_CONFIG = {
  version: 2,
  colors: {
    brandInk: '#300101',
    brandCanvas: '#FFFEFC',
    actionPrimary: '#2216FF',
    actionPrimaryHover: '#1B11CC',
    textPrimary: '#300101',
    textSecondary: '#64645F',
    textOnDark: '#FFFEFC',
    borderDefault: '#E0E0DC',
    borderFocus: '#2216FF',
    accentOrange: '#F58E39',
  },
  typography: {
    brandFont: 'Plus Jakarta Sans',
    bodyFont: 'DM Sans',
    inputFont: 'Inter',
    headlineSize: '36',
    formTitleSize: '22',
    bodySize: '16',
    headlineWeight: '800',
  },
  content: {
    logoText: 'klasse',
    headlineLine1: 'Turn what you know',
    headlineLine2: 'into courses people',
    headlineAccent: 'love',
    subheadline: 'The simplest way to create, publish, and sell structured learning paths. Built for creators who care about their learners.',
    formTitle: 'Create your account',
    formSubtitle: 'Start building in under 2 minutes',
    submitButtonText: 'Create Account',
    googleButtonText: 'Continue with Google',
    dividerText: 'or sign up with email',
    signinPrompt: 'Already have an account?',
    signinLinkText: 'Sign in',
  },
  cards: [
    { title: 'Cooking for One: Quick Weeknight Meals', instructor: 'Sarah Chen', lessons: '8 lessons', price: '$39', badge: 'Popular', emoji: '\u{1F373}', gradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 50%, #d97706 100%)', dotGradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 100%)', visible: true },
    { title: 'Home Workout Blueprint: No Equipment', instructor: 'Alex Rivera', lessons: '6 lessons', price: 'Free', badge: 'New', emoji: '', gradient: 'linear-gradient(135deg, #6ee7b7 0%, #10b981 50%, #047857 100%)', dotGradient: 'linear-gradient(135deg, #6ee7b7 0%, #10b981 100%)', visible: true },
    { title: 'Web Development Basics: Create your first site', instructor: 'Jamie Lee', lessons: '10 lessons', price: '$49', badge: 'Trending', emoji: '\u{1F5A5}\u{FE0F}', gradient: 'linear-gradient(135deg, #c4b5fd 0%, #7c3aed 50%, #5b21b6 100%)', dotGradient: 'linear-gradient(135deg, #c4b5fd 0%, #7c3aed 100%)', visible: true },
    { title: 'Guitar Mastery: From Beginner to Pro', instructor: 'Leo Grant', lessons: '15 lessons', price: '\u20AC75', badge: 'Featured', emoji: '\u{1F3B8}', gradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 50%, #d97706 100%)', dotGradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 100%)', visible: true },
    { title: 'Brand Identity Design from Scratch', instructor: 'Mia Park', lessons: '12 lessons', price: '\u20AC59', badge: 'Bestseller', emoji: '\u{1F3A8}', gradient: 'linear-gradient(135deg, #c4b5fd 0%, #7c3aed 50%, #5b21b6 100%)', dotGradient: 'linear-gradient(135deg, #c4b5fd 0%, #7c3aed 100%)', visible: true },
  ],
  layout: {
    showBrowserChrome: false,
    showGoogleButton: true,
    showDivider: true,
    showCourseCards: true,
    showTerms: true,
    borderRadius: '8',
    brandPanelPosition: 'left',
  },
}
